### PR TITLE
Update Readme.md and contribute.md

### PR DESCRIPTION
**Pull request by sakshi2912**
## Summary

The repeated section of "contribute" has been removed from README.md, as it is already a part of CONTRIBUTE.md. 
Shifted the "contributers" section to CONTRIBUTE.md.

### CODE REVIEW

**Comment by balazsbotond** [comment]
Thanks for your PR but would you please fill out the PR template and explain why you made these changes?

**Comment by bmnidhin** [comment]
**Probably a spam.** 


@sakshi2912 Just moved contents from README.md to CONTRIBUTING.md

**Comment by bmnidhin** [comment]
> 
> 
> **Probably a spam.**
> 
> @sakshi2912 Just moved contents from README.md to CONTRIBUTING.md

@balazsbotond

**Comment by sakshi2912** [comment]
> **Probably a spam.**
> 
> @sakshi2912 Just moved contents from README.md to CONTRIBUTING.md

It was in one of the open issues.

**Comment by sakshi2912** [comment]
> > **Probably a spam.**
> > @sakshi2912 Just moved contents from README.md to CONTRIBUTING.md
> 
> It was in one of the open issues.

#63

**Comment by balazsbotond** [comment]
@sakshi2912 I see. The documentation is on the `gh-pages` branch. Could you please create a new PR against that branch? This wasn't described in the issue you referenced so you couldn't have known.

A piece of advice: it is considered good form to write a description for the PRs you open, however trivial, and reference any relevant issues. This way misunderstandings like what happened here can be prevented.

Thanks again for your interest in the project and feel free to ask any further questions you have here in the comments.

**Comment by sakshi2912** [comment]
> @sakshi2912 I see. The documentation is on the `gh-pages` branch. Could you please create a new PR against that branch? This wasn't described in the issue you referenced so you couldn't have known.
> 
> A piece of advice: it is considered good form to write a description for the PRs you open, however trivial, and reference any relevant issues. This way misunderstandings like what happened here can be prevented.
> 
> Thanks again for your interest in the project and feel free to ask any further questions you have here in the comment.

Sure, will do that.

**Pull request closed without merging**
