### PR TITLE
Query param bug solve

### PR DESCRIPTION
**Pull request by harshilparmar**
@balazsbotond  As you said https://github.com/balazsbotond/urlcat/pull/115#issuecomment-743730898
I have made separate change.Please check !!

### CODE REVIEW

**Comment by harshilparmar** [comment]
@balazsbotond bro Can you look at last build error ? I don't have idea about deno 🆘

**Comment by balazsbotond** [comment]
> @balazsbotond bro Can you look at last build error ? I don't have idea about deno

Looks like the deno linter is complaining because of our use of `any` in the definition of `ParamMap`. You can disable this warning by putting this comment:

```typescript
// deno-lint-ignore no-explicit-any
```

before the offending line (see: https://deno.land/manual@v1.4.0/tools/linter).

**Comment by harshilparmar** [comment]
> ```ts
> // deno-lint-ignore no-explicit-any
> ```
@balazsbotond  Perfect !! its working 🎉

**Review by balazsbotond — APPROVED** [review]
Thank you! I'm merging this now and I will publish a new version later today.

**Pull request merged**
